# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NuBits
email: info@nubits.com
description: "World's Best Stable Digital Currencies"
url: "https://jooize.github.io" # with the https protocol
baseurl: "/nunetwork.github.io" # the subpath of your site, e.g. /blog
enforce_ssl: "jooize.github.io/nunetwork.github.io/" # without any protocol

# Build settings
markdown: kramdown

sass:
  style: compressed

include: ["_pages"]

#menu-list: ["Exchanges", "Explorer", "Discuss", "Wallets"]

menu-list: ["Exchanges", "Explorer", "Discuss", "Wallet"]

plugins:
  - jekyll-redirect-from
